import type { PortfolioItem } from "./types";

/** Shared Promptstack web-design portfolio (owned work). */
const basePortfolioItems: Omit<PortfolioItem, "href">[] = [
  {
    id: "pf-finance",
    slug: "finance-web-design",
    title: "Finance Web Design",
    category: "Finance",
    imageSrc: "/brand/portfolio/finance-web-design.png",
    imageAlt: "Finance web design project",
  },
  {
    id: "pf-photography",
    slug: "photography-web-design",
    title: "Photography Web Design",
    category: "Photography",
    imageSrc: "/brand/portfolio/photography-web-design.png",
    imageAlt: "Photography web design project",
  },
  {
    id: "pf-makeup",
    slug: "makeup-web-design",
    title: "Makeup Web Design",
    category: "Beauty",
    imageSrc: "/brand/portfolio/makeup-web-design.png",
    imageAlt: "Makeup web design project",
  },
  {
    id: "pf-business",
    slug: "business-web-design",
    title: "Business Web Design",
    category: "Business",
    imageSrc: "/brand/portfolio/business-web-design.png",
    imageAlt: "Business web design project",
  },
  {
    id: "pf-crypto",
    slug: "crypto-web-design",
    title: "Crypto Web Design",
    category: "Crypto",
    imageSrc: "/brand/portfolio/crypto-web-design.png",
    imageAlt: "Crypto web design project",
  },
  {
    id: "pf-beauty",
    slug: "beauty-web-design",
    title: "Beauty Web Design",
    category: "Beauty",
    imageSrc: "/brand/portfolio/beauty-web-design.png",
    imageAlt: "Beauty web design project",
  },
  {
    id: "pf-homecare",
    slug: "homecare-web-design",
    title: "HomeCare Web Design",
    category: "Home care",
    imageSrc: "/brand/portfolio/homecare-web-design.jpg",
    imageAlt: "Home care web design project",
  },
  {
    id: "pf-tempnumber",
    slug: "temporary-number",
    title: "Temporary Number",
    category: "Product",
    imageSrc: "/brand/portfolio/temporary-number.png",
    imageAlt: "Temporary number web design project",
  },
  {
    id: "pf-fashion-portfolio",
    slug: "fashion-portfolio-design",
    title: "Fashion Portfolio Design",
    category: "Fashion",
    imageSrc: "/brand/portfolio/fashion-portfolio-design.png",
    imageAlt: "Fashion portfolio web design project",
  },
  {
    id: "pf-homecare-2",
    slug: "homecare-web-design-2",
    title: "HomeCare Web Design",
    category: "Home care",
    imageSrc: "/brand/portfolio/homecare-web-design-2.png",
    imageAlt: "Home care web design project",
  },
  {
    id: "pf-lady-care",
    slug: "lady-care-design",
    title: "Lady Care Design",
    category: "Beauty",
    imageSrc: "/brand/portfolio/lady-care-design.png",
    imageAlt: "Lady care web design project",
  },
  {
    id: "pf-body-trimmer",
    slug: "body-trimmer-design",
    title: "Body Trimmer Design",
    category: "Product",
    imageSrc: "/brand/portfolio/body-trimmer-design.png",
    imageAlt: "Body trimmer web design project",
  },
  {
    id: "pf-fashion-brand",
    slug: "fashion-brand-design",
    title: "Fashion Brand Design",
    category: "Fashion",
    imageSrc: "/brand/portfolio/fashion-brand-design.png",
    imageAlt: "Fashion brand web design project",
  },
  {
    id: "pf-fashion-brand-2",
    slug: "fashion-brand-design-2",
    title: "Fashion Brand Design",
    category: "Fashion",
    imageSrc: "/brand/portfolio/fashion-brand-design-2.png",
    imageAlt: "Fashion brand web design project",
  },
  {
    id: "pf-food",
    slug: "food-web-design",
    title: "Food Web Design",
    category: "Food",
    imageSrc: "/brand/portfolio/food-web-design.png",
    imageAlt: "Food web design project",
  },
  {
    id: "pf-brand",
    slug: "brand-web-design",
    title: "Brand Web Design",
    category: "Brand",
    imageSrc: "/brand/portfolio/brand-web-design.png",
    imageAlt: "Brand web design project",
  },
  {
    id: "pf-ecommerce",
    slug: "ecommerce-web-design",
    title: "E-commerce Web Design",
    category: "E-commerce",
    imageSrc: "/brand/portfolio/ecommerce-web-design.png",
    imageAlt: "E-commerce web design project",
  },
  {
    id: "pf-fx",
    slug: "fx-web-design",
    title: "FX Web Design",
    category: "Finance",
    imageSrc: "/brand/portfolio/fx-web-design.jpg",
    imageAlt: "FX web design project",
  },
  {
    id: "pf-crypto-2",
    slug: "crypto-web-design-2",
    title: "Crypto Web Design",
    category: "Crypto",
    imageSrc: "/brand/portfolio/crypto-web-design-2.png",
    imageAlt: "Crypto web design project",
  },
  {
    id: "pf-company",
    slug: "company-web-design",
    title: "Company Web Design",
    category: "Company",
    imageSrc: "/brand/portfolio/company-web-design.png",
    imageAlt: "Company web design project",
  },
  {
    id: "pf-church",
    slug: "church-web-design",
    title: "Church Web Design",
    category: "Faith",
    imageSrc: "/brand/portfolio/church-web-design.png",
    imageAlt: "Church web design project",
  },
  {
    id: "pf-ngo",
    slug: "ngo-web-design",
    title: "NGO Web Design",
    category: "NGO",
    imageSrc: "/brand/portfolio/ngo-web-design.png",
    imageAlt: "NGO web design project",
  },
  {
    id: "pf-hosting",
    slug: "hosting-web-design",
    title: "Hosting Web Design",
    category: "Hosting",
    imageSrc: "/brand/portfolio/hosting-web-design.png",
    imageAlt: "Hosting web design project",
  },
  {
    id: "pf-jewelry",
    slug: "jewelry-web-design",
    title: "Jewelry Web Design",
    category: "Jewelry",
    imageSrc: "/brand/portfolio/jewelry-web-design.png",
    imageAlt: "Jewelry web design project",
  },
  {
    id: "pf-hair",
    slug: "hair-vendor-web-design",
    title: "Hair Vendor Web Design",
    category: "Beauty",
    imageSrc: "/brand/portfolio/hair-vendor-web-design.png",
    imageAlt: "Hair vendor web design project",
  },
  {
    id: "pf-academia",
    slug: "academia-web-design",
    title: "Academia Web Design",
    category: "Education",
    imageSrc: "/brand/portfolio/academia-web-design.png",
    imageAlt: "Academia web design project",
  },
  {
    id: "pf-research",
    slug: "research-web-design",
    title: "Research Web Design",
    category: "Research",
    imageSrc: "/brand/portfolio/research-web-design.png",
    imageAlt: "Research web design project",
  },
  {
    id: "pf-agency",
    slug: "agency-web-design",
    title: "Agency Web Design",
    category: "Agency",
    imageSrc: "/brand/portfolio/agency-web-design.png",
    imageAlt: "Agency web design project",
  },
  {
    id: "pf-abstract",
    slug: "abstract-web-design",
    title: "Abstract Web Design",
    category: "Creative",
    imageSrc: "/brand/portfolio/abstract-web-design.png",
    imageAlt: "Abstract web design project",
  },
];

export const portfolioItemsEn: PortfolioItem[] = basePortfolioItems.map((item) => ({
  ...item,
  href: `/portfolio/${item.slug}`,
}));

export const portfolioItemsFr: PortfolioItem[] = portfolioItemsEn.map((item) => ({
  ...item,
  title: item.title
    .replace("Web Design", "Design web")
    .replace("Portfolio Design", "Design portfolio")
    .replace("Brand Design", "Design de marque")
    .replace("Lady Care Design", "Design Lady Care")
    .replace("Body Trimmer Design", "Design Body Trimmer")
    .replace("Temporary Number", "Temporary Number")
    .replace("E-commerce", "E-commerce"),
  category: ({
    Finance: "Finance",
    Photography: "Photographie",
    Beauty: "Beauté",
    Business: "Business",
    Crypto: "Crypto",
    "Home care": "Aide à domicile",
    Product: "Produit",
    Fashion: "Mode",
    Food: "Food",
    Brand: "Marque",
    "E-commerce": "E-commerce",
    Company: "Entreprise",
    Faith: "Foi",
    NGO: "ONG",
    Hosting: "Hébergement",
    Jewelry: "Bijoux",
    Education: "Éducation",
    Research: "Recherche",
    Agency: "Agence",
    Creative: "Créatif",
  }[item.category] || item.category),
  imageAlt: item.imageAlt?.replace("web design project", "projet de design web"),
}));
